<a href="https://colab.research.google.com/github/manoj-b-22/IDS-in-IoV/blob/main/Copy_of_ML_intra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn import svm
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
data = pd.read_csv('/content/drive/MyDrive/intravehicle.csv')

In [ ]:
y_data = data.pop('4')
x_data = data

In [ ]:
train_x,test_x,train_y,test_y = train_test_split(x_data, y_data, test_size=0.2, random_state=0, shuffle=True) 

In [ ]:
train_x = train_x.reset_index(drop=True)
test_x = test_x.reset_index(drop=True) 
train_y = train_y.reset_index(drop=True)
test_y = test_y.reset_index(drop=True)

In [ ]:
scaler = StandardScaler()
train_x = scaler.fit_transform(train_x)
test_x = scaler.transform(test_x)

In [ ]:
encoder = LabelEncoder()
train_y = encoder.fit_transform(train_y)
test_y = encoder.transform(test_y)

In [ ]:
def printReport(test_y,predict_y):
  accuracy = accuracy_score(test_y, predict_y)
  print('Accuracy: %.6f' % accuracy)
  print()

  # T up-down  F left-right
  print('Confusion Matrix')                      #  TP FP
  print(confusion_matrix(test_y, predict_y))      #  FN TN 
  print()
  
  print(classification_report(test_y, predict_y, digits=6))

In [ ]:
n=5
classifier = KNeighborsClassifier(n_neighbors=n, metric='minkowski', algorithm='kd_tree', n_jobs=-1)
classifier.fit(train_x,train_y)

predict_y = classifier.predict(test_x)

print('K-Nearest Neighbour Classifier\n')
printReport(test_y,predict_y)

K-Nearest Neighbour Classifier

Accuracy: 0.999748

Confusion Matrix
[[ 117727       0       0       0]
 [      0   97406     796       0]
 [      0      40 2847870       0]
 [      0       0       0  250056]]

              precision    recall  f1-score   support

           0   1.000000  1.000000  1.000000    117727
           1   0.999590  0.991894  0.995727     98202
           2   0.999721  0.999986  0.999853   2847910
           3   1.000000  1.000000  1.000000    250056

    accuracy                       0.999748   3313895
   macro avg   0.999828  0.997970  0.998895   3313895
weighted avg   0.999748  0.999748  0.999747   3313895



In [ ]:
classifier = LogisticRegression(multi_class='multinomial', solver='sag', random_state=0, max_iter=1000, n_jobs=-1)
classifier.fit(train_x,train_y)

predict_y = classifier.predict(test_x)

print('Logistic Regression\n')
printReport(test_y,predict_y)

Logistic Regression

Accuracy: 0.883056

Confusion Matrix
[[ 117727       0       0       0]
 [      2       0   98164      36]
 [      0       0 2808628   39282]
 [      0       0  250056       0]]



/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

           0   0.999983  1.000000  0.999992    117727
           1   0.000000  0.000000  0.000000     98202
           2   0.889694  0.986207  0.935468   2847910
           3   0.000000  0.000000  0.000000    250056

    accuracy                       0.883056   3313895
   macro avg   0.472419  0.496552  0.483865   3313895
weighted avg   0.800114  0.883056  0.839451   3313895



/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
model = RandomForestClassifier(random_state=0, n_jobs=-1)
model.fit(train_x, train_y)

predict_y = model.predict(test_x)

print('Random Forest Classifier\n')
printReport(test_y,predict_y)

Random Forest Classifier

Accuracy: 0.999984

Confusion Matrix
[[ 117727       0       0       0]
 [      0   98151      51       0]
 [      0       1 2847909       0]
 [      0       0       0  250056]]

              precision    recall  f1-score   support

           0   1.000000  1.000000  1.000000    117727
           1   0.999990  0.999481  0.999735     98202
           2   0.999982  1.000000  0.999991   2847910
           3   1.000000  1.000000  1.000000    250056

    accuracy                       0.999984   3313895
   macro avg   0.999993  0.999870  0.999932   3313895
weighted avg   0.999984  0.999984  0.999984   3313895



In [ ]:
classifier = svm.SVC(random_state=0, kernel='rbf', decision_function_shape='ovr')
classifier.fit(train_x,train_y)

predict_y = classifier.predict(test_x)

print('Support Vector Machine\n')
printReport(test_y,predict_y)