<a href="https://colab.research.google.com/github/manoj-b-22/IDS-in-IoV/blob/main/code/ML-inter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn import svm
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
scaler = StandardScaler()
encoder = LabelEncoder()

In [4]:
train = pd.read_csv('/content/drive/MyDrive/train-intervehicle.csv', chunksize=500000)
test = pd.read_csv('/content/drive/MyDrive/test-intervehicle.csv')

In [5]:
def printReport(test_y,predict_y):
  accuracy = accuracy_score(test_y, predict_y)
  print('Accuracy: %.7f' % accuracy)
  print()

  # T up-down  F left-right
  print('Confusion Matrix')                       #  TP FP
  print(confusion_matrix(test_y, predict_y))      #  FN TN 
  print()

  print(classification_report(test_y, predict_y, digits=6))

In [6]:
n=5
KNN = KNeighborsClassifier(n_neighbors=n, metric='minkowski', algorithm='kd_tree', n_jobs=-1)

In [7]:
LR = LogisticRegression(random_state=0, max_iter=1000, solver='sag', n_jobs=-1, warm_start=True)

In [8]:
RF = RandomForestClassifier(random_state=0, n_jobs=-1, warm_start=True)

In [9]:
SVM = svm.SVC(random_state=0, kernel='rbf')

In [10]:
for chunk in train:
  train_y = chunk.pop('Label')
  train_x = chunk
  train_x = scaler.fit_transform(train_x)
  train_y = encoder.fit_transform(train_y)
  KNN.fit(train_x, train_y) # fit 
  LR.fit(train_x, train_y)
  RF.fit(train_x, train_y)
  SVM.fit(train_x, train_y) # fit 

/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_sag.py:352: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_sag.py:352: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/ensemble/_forest.py:429: UserWarning: Warm-start fitting without increasing n_estimators does not fit new trees.
  warn(
/usr/local/lib/python3.8/dist-packages/sklearn/ensemble/_forest.py:429: UserWarning: Warm-start fitting without increasing n_estimators does not fit new trees.
  warn(
/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_sag.py:352: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/ensemble/_forest.py:429: UserWarning: Warm-start fitting without increasing n_estimators does n

In [11]:
test_y = test.pop('Label')
test_x = test

In [12]:
test_x = scaler.transform(test_x)
test_y = encoder.transform(test_y)

In [13]:
predict_y = KNN.predict(test_x)

print('K-Nearest Neighbour Classifier\n')
printReport(test_y, predict_y)

K-Nearest Neighbour Classifier

Accuracy: 0.9997258

Confusion Matrix
[[1255245     496]
 [    203 1293344]]

              precision    recall  f1-score   support

           0   0.999838  0.999605  0.999722   1255741
           1   0.999617  0.999843  0.999730   1293547

    accuracy                       0.999726   2549288
   macro avg   0.999727  0.999724  0.999726   2549288
weighted avg   0.999726  0.999726  0.999726   2549288



In [14]:
predict_y = LR.predict(test_x)

print('Logistic Regression\n')
printReport(test_y, predict_y)

Logistic Regression

Accuracy: 0.9952430

Confusion Matrix
[[1248766    6975]
 [   5152 1288395]]

              precision    recall  f1-score   support

           0   0.995891  0.994446  0.995168   1255741
           1   0.994615  0.996017  0.995316   1293547

    accuracy                       0.995243   2549288
   macro avg   0.995253  0.995231  0.995242   2549288
weighted avg   0.995244  0.995243  0.995243   2549288



In [15]:
predict_y = RF.predict(test_x)

print('Random Forest Classifier\n')
printReport(test_y, predict_y)

Random Forest Classifier

Accuracy: 0.9210391

Confusion Matrix
[[1255741       0]
 [ 201294 1092253]]

              precision    recall  f1-score   support

           0   0.861847  1.000000  0.925798   1255741
           1   1.000000  0.844386  0.915628   1293547

    accuracy                       0.921039   2549288
   macro avg   0.930923  0.922193  0.920713   2549288
weighted avg   0.931948  0.921039  0.920638   2549288



In [16]:
predict_y = SVM.predict(test_x)

print('Support Vector Machine\n')
printReport(test_y, predict_y)

Support Vector Machine

Accuracy: 0.9997344

Confusion Matrix
[[1255303     438]
 [    239 1293308]]

              precision    recall  f1-score   support

           0   0.999810  0.999651  0.999730   1255741
           1   0.999661  0.999815  0.999738   1293547

    accuracy                       0.999734   2549288
   macro avg   0.999736  0.999733  0.999734   2549288
weighted avg   0.999734  0.999734  0.999734   2549288

